services:
  postgres:
    image: postgres:15
    restart: always
    container_name: services_postgres_prod
    env_file:
      - ./apps/api/.env.production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    restart: always
    env_file:
      - ./apps/api/.env.production
    depends_on:
      - postgres
    ports:
      - "5175:5175"

  web:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: web
    restart: always
    env_file:
      - ./apps/frontend/.env.production
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  postgres_data:
