services:
  postgres:
    image: postgres:15
    restart: always
    container_name: services_postgres
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
